// <auto-generated />
using System;
using GestorTarea.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorTarea.Migrations
{
    [DbContext(typeof(GestorTareasContext))]
    [Migration("20260506113349_SincronizarColumnas")]
    partial class SincronizarColumnas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorTarea.Domain.Entities.Tarea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Diainicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ID");

                    b.ToTable("Tareas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaConTarea", b =>
                {
                    b.HasBaseType("GestorTarea.Domain.Entities.Tarea");

                    b.Property<string>("InstruccionesDependencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TareaDependienteID")
                        .HasColumnType("int");

                    b.ToTable("TareasConTarea", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaPomodoro", b =>
                {
                    b.HasBaseType("GestorTarea.Domain.Entities.Tarea");

                    b.Property<DateTime>("TiempoFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TiempoInit")
                        .HasColumnType("datetime2");

                    b.ToTable("TareasPomodoro", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaRecurrente", b =>
                {
                    b.HasBaseType("GestorTarea.Domain.Entities.Tarea");

                    b.PrimitiveCollection<string>("IntervalosEnDias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TareasRecurrentes", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaSimple", b =>
                {
                    b.HasBaseType("GestorTarea.Domain.Entities.Tarea");

                    b.ToTable("TareasSimples", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaUrgente", b =>
                {
                    b.HasBaseType("GestorTarea.Domain.Entities.Tarea");

                    b.ToTable("TareasUrgentes", (string)null);
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaConTarea", b =>
                {
                    b.HasOne("GestorTarea.Domain.Entities.Tarea", null)
                        .WithOne()
                        .HasForeignKey("GestorTarea.Domain.Entities.TareaConTarea", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaPomodoro", b =>
                {
                    b.HasOne("GestorTarea.Domain.Entities.Tarea", null)
                        .WithOne()
                        .HasForeignKey("GestorTarea.Domain.Entities.TareaPomodoro", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaRecurrente", b =>
                {
                    b.HasOne("GestorTarea.Domain.Entities.Tarea", null)
                        .WithOne()
                        .HasForeignKey("GestorTarea.Domain.Entities.TareaRecurrente", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaSimple", b =>
                {
                    b.HasOne("GestorTarea.Domain.Entities.Tarea", null)
                        .WithOne()
                        .HasForeignKey("GestorTarea.Domain.Entities.TareaSimple", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTarea.Domain.Entities.TareaUrgente", b =>
                {
                    b.HasOne("GestorTarea.Domain.Entities.Tarea", null)
                        .WithOne()
                        .HasForeignKey("GestorTarea.Domain.Entities.TareaUrgente", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
